### ISSUE TITLE
there is some errors, when execute "make"

### ISSUE THREAD

**Issue by simpler66** [robertoffmoura/waterpixels#1]
thanks for your great job!
there are some errors when execute "make".
do you have any idea about how to fix it?

XXX@XXX:~/Downloads/waterpixels-master/build$ make
[ 42%] Built target waterpixels_example
Scanning dependencies of target waterpixels_metrics
[ 57%] Building CXX object CMakeFiles/waterpixels_metrics.dir/metrics.cpp.o
[ 71%] Building CXX object CMakeFiles/waterpixels_metrics.dir/waterpixels.cpp.o
[ 85%] Building CXX object CMakeFiles/waterpixels_metrics.dir/metricsLibrary.cpp.o
/home/lbr/Downloads/waterpixels-master/metricsLibrary.cpp: In function ‘pi getCenter(std::unordered_set<std::pair<int, int>, pair_hash>)’:
/home/lbr/Downloads/waterpixels-master/metricsLibrary.cpp:15:41: error: ‘round’ was not declared in this scope
  return std::make_pair(round(i_sum/total), round(j_sum/total));
                                         ^
/home/lbr/Downloads/waterpixels-master/metricsLibrary.cpp: In member function ‘int MetricsLibrary::getDistanceToLabel(int, std::vector<bool>)’:
/home/lbr/Downloads/waterpixels-master/metricsLibrary.cpp:152:9: error: ‘INT_MAX’ was not declared in this scope
  return INT_MAX;
         ^
CMakeFiles/waterpixels_metrics.dir/build.make:88: recipe for target 'CMakeFiles/waterpixels_metrics.dir/metricsLibrary.cpp.o' failed
make[2]: *** [CMakeFiles/waterpixels_metrics.dir/metricsLibrary.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/waterpixels_metrics.dir/all' failed
make[1]: *** [CMakeFiles/waterpixels_metrics.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by robertoffmoura** [comment]
Hey there, try changing 'round' to 'std::round' and add '#include \<climits\>' to the top of metricsLibrary.cpp.
I added these changes in 7be7eeee4546fb69c372cd7abc6e2c4f64e7fc4a. Hopefully it should work!

**Comment by simpler66** [comment]
> Hey there, try changing 'round' to 'std::round' and add '#include <climits>' to the top of metricsLibrary.cpp.
> I added these changes in [7be7eee](https://github.com/robertoffmoura/waterpixels/commit/7be7eeee4546fb69c372cd7abc6e2c4f64e7fc4a). Hopefully it should work!

thanks, it works!
